### ISSUE TITLE
Can't find black when installed into venv

### ISSUE THREAD

**Issue by pzelnip** [joslarson/black-vscode#1]
I installed Black into a virtual environment, and every time I try to format I get:
```
Command "black" not found in PATH.  Try `pip install black`
```
If I install systemwide the error goes away.  Would be nice to not have to install system-wide, much like I don't with tools like autopep8 or pylint.

**Comment by joslarson** [comment]
@pzelnip I'm assuming you want it to respect the Python environment set by the Python extension, is that right? I agree that's something that should be added. But as a work around, what I'm doing currently is launching vscode as a subprocess of a shell with my virtual environment activated.

**Comment by pzelnip** [comment]
Correct, I'd expect the `python.pythonPath` setting to be used.

**Comment by joslarson** [comment]
@pzelnip just published a fix for this. Thanks for the heads up :)
