### ISSUE TITLE
Support for suppressing unable to parse error message

### ISSUE THREAD

**Issue by PowerSnail** [joslarson/black-vscode#15]
Hi, is it possible to add an option that suppress the "unable to parse" message?

I often turn on "format-on-save" option in vscode. But every time I save at the middle of work where there is a broken syntax, black will report an error. Given how vscode handles such notifications, that error message persists, until I use my mouse to click "x".

Since black is not a linter, I suppose that it could just silently leave the file unchanged if the file has syntax errors.

Thank you for this amazing tool.

**Comment by joslarson** [comment]
@PowerSnail Agreed, this would be a nice addition, but Black formatting support just landed in the latest official Python extension, so you might want to switch to that. My plan all along has been to deprecate this extension once the official Python extension added support for Black. Let me know if there's any reason I shouldn't go ahead with that course of action.

**Comment by joslarson** [comment]
After some feedback from those who have switched, I've officially deprecated this extension in favor of the official Python extension. Thanks for taking the time to create this issue. I'm going to go ahead and close it, but feel free to comment if there's any reason it should be reopened.
