### ISSUE TITLE
`Failed to format: unknown error.` on every attempt to format

### ISSUE THREAD

**Issue by pzelnip** [joslarson/black-vscode#2]
Every source file I've tried so far, when I go to Format -> Document, I get a notification saying: `Failed to format: unknown error.`

VSCode version: 1.21.1
Python version: 3.6.2
OS: OSX 10.12.6 (Sierra)

Some of the source files I can't share (company owned), but one example that failed that I can share (though as I said every file I've tried produced the same error):

```
from setuptools import setup


def readme():
    with open('README.md') as f:
        return f.read()


setup(name='thethingy',
      version='0.1.1',
      description='CLI tool for stuff',
      long_description=readme(),
      classifiers=[
          'Development Status :: 3 - Alpha',
          'Programming Language :: Python :: 2.7',
      ],
      keywords='blargyblarg aws',
      url='http://foo.bar/baz',
      author='Me',
      author_email='',
      license='Internal Use',
      install_requires=[
          'beautifulsoup4',
          'awscli',
          'boto',
          'requests-ntlm',
      ],
      scripts=['bin/mytestscript.py'],
      include_package_data=True,
      zip_safe=False)
```

**Comment by joslarson** [comment]
@pzelnip can you try this again with the new version (v1.1.0) that I just pushed out? I'm unable to reproduce this so far.

**Comment by pzelnip** [comment]
Completely uninstalled both Black & the VSCode plugin.  Reinstalled and got same error.

```
$ black --version
black, version 18.3a3
```
and VS Code is reporting version 1.2.0 of the plugin.

<img width="1077" alt="screen shot 2018-03-22 at 7 47 41 am" src="https://user-images.githubusercontent.com/414933/37777686-64c6c93a-2da5-11e8-806b-513fa5613592.png">

**Comment by pzelnip** [comment]
And now I can't seem to uninstall the VSCode plugin.  Every time I click reload after uninstalling it re-appears int the installed plugins list.  See screen recording of what I'm talking about: https://www.dropbox.com/sh/17z5mgltwccd94d/AADhbf6e62QzMz20hHV3Slora?dl=0

I looked in my ~/.vscode/extensions directory and there were two versions of the joslarson.black-vscode extension installed.  I manually `rm -rf`'d both, and it was then gone from the list of installed extensions.

I tried reinstalling, and got the same error when trying to format.

Afterwards tried uninstalling from the VSCode marketplace and same issue -- couldn't seem to uninstall.  Looked again in my ~/.vscode/extensions folder and there was one entry this time (1.2.0).  Again, had to manually `rm -rf` it to get it uninstalled.

**Comment by joslarson** [comment]
@pzelnip I've seen odd uninstall behavior like you mentioned with extensions in the past, but it usually had to do with the fact that vscode doesn't actually remove the extension until you have completely exited out of vscode (not just a workspace) and then reopened it.

To help with the main issue here though, what value's do you have set for the following settings:  `python.pythonPath`, `black.path`?

**Comment by joslarson** [comment]
@pzelnip also I just published v1.2.2 which has a new undocumented `black.debug` setting. If you set that to `true`, each time you format your code you will get the output of the command that is being run as well as any resulting errors. Can you also let me know what you get in your case with that?

**Comment by rsnk96** [comment]
I faced the same problem @pzelnip @joslarson. In my case, it was cause by a black dependency being outdated. I fixed it by running
```
pip install attrs==17.4
```

Note: Running `pip install attrs -U` said attrs was updated for some reason, while it was still version `17.2.0` (which you can check by running `pip list`)

I am using Anaconda Python 3.6.0 on an Ubuntu 16.04 system

**Comment by joslarson** [comment]
@pzelnip I haven't heard from you in a few days. You still having issues, or can I close this issue?

**Comment by joslarson** [comment]
@pzelnip I'm going to assume this issue is resolved. If you're still having problems with what you mentioned above, just comment on here and I'd be happy to reopen the issue.
