### ISSUE TITLE
Configurable black path

### ISSUE THREAD

**Issue by dusty-phillips** [joslarson/black-vscode#3]
I'm getting lost in a sea of virtual environments. Can we have `"python.formatting.blackPath"` not unlike `"python.formatting.yapfPath"`?

**Comment by joslarson** [comment]
@buchuki thanks for submitting this issue 👍 Setting the `python.pythonPath` setting, should guarantee the version of black in that python environment is run. Does that solve your issue, or am I missing something?

**Comment by dusty-phillips** [comment]
@joslarson I actually want to run black from a different environment from my `pythonPath`. I'm editing pypy3.5 code and I have my `pythonPath` set to that virtualenv for the appropriate requirements, tests, etc. But I want to run black from my `python 3.6` environment.

**Comment by joslarson** [comment]
That makes a lot of sense. I'll try and look into it tonight.

**Comment by joslarson** [comment]
@buchuki I just published v1.2.0 with a new `black.path` setting. Should give you what you're after :) thanks for the feedback.

**Comment by dusty-phillips** [comment]
Thanks so much, it's working great!
