### ISSUE TITLE
Add instructions on how to format in VS Code to README

### ISSUE THREAD

**Issue by zain** [joslarson/black-vscode#5]
I installed this extension but I can't figure out how to make it format my Python files. Is there a command or something?

**Comment by joslarson** [comment]
Agreed the README could be improved. Are you just wondering how to format code in VS Code in general? If so, formatter extensions adhere to a standard API, so this extension just registers it self as a formatter for Python files. The way you format any code in vscode is by running the "Format Document" or "Format Selection" commands, which can be found via `cmd/ctrl` + `shift` + `p` then searching for those command names (they also have dedicated keyboard shortcuts).

**Comment by joslarson** [comment]
@zain also make sure you have the most recent version of both black and the extension. Black v18.4a4 changed the command line API, so I just pushed v2.0.0 of the extension with breaking changes from v1.3.1.

**Comment by shacker** [comment]
> The way you format any code in vscode is by running the "Format Document" 

Ah! Thanks. I had Black working from CLI, installed the extension into VSCode, and did Cmd+Shift+P "black" and got nothing. Was puzzled and thought I hadn't installed it correctly. Yes, this definitely could be pointed out  in the readme.

**Comment by pauloneves** [comment]
A link to configure the standard format would also be nice. I selected _Format code with standard-format_ and got an error: _running the contribute command format.standard failed_

A tip for autoformatting on save would also be nice.

**Comment by paddie** [comment]
@joslarson I added a PR to address some of the documentation. Let me know what you think.
