### ISSUE TITLE
Format Document does nothing

### ISSUE THREAD

**Issue by Tinche** [joslarson/black-vscode#6]
Sorry, it's me again :)

Version 1.3.1, picking Format Document from the command palette does nothing. I have debug: true, and the debug output does open (and "Black - Python code formatter" is selected) but only a single empty line gets output.

**Comment by joslarson** [comment]
@Tinche Yikes, at this point I'm the one that's sorry it's you again 😞 but I do appreciate you helping me figure out some of these edge cases. Sounds like there's an unhandled error being thrown.

To help me recreate your environment, your `pythonPath` in your workspace settings is set to "${workspaceFolder}/.venv-cpython3.6/bin/python" right? And running `./.venv-cpython3.6/bin/python -m black --help` prints out black's help? Also have you customized the `black.path` setting at all?

**Comment by Tinche** [comment]
<img width="616" alt="screen shot 2018-03-26 at 17 19 53" src="https://user-images.githubusercontent.com/1909233/37915534-087c164e-311a-11e8-86d7-80f24fdf0a1b.png">
<img width="821" alt="screen shot 2018-03-26 at 17 20 10" src="https://user-images.githubusercontent.com/1909233/37915541-0c245d74-311a-11e8-871d-fc434f038391.png">

Here we go :)

**Comment by joslarson** [comment]
@Tinche I figured it out, v18.3a4 of black changed how exit codes work.

**Comment by Tinche** [comment]
Awesome!

**Comment by joslarson** [comment]
@Tinche try v2.0.0, that should fix the issue :) It had to be a breaking change, hopefully blacks api is stabilizing.

**Comment by Tinche** [comment]
It works! Thanks a lot!
