### ISSUE TITLE
Support env variable expansion in "python.pythonPath" setting

### ISSUE THREAD

**Issue by mhubig** [joslarson/black-vscode#8]
Hi there,
I was just trying your extension but unfortunately it doesn't format my code at all. Im using:

```
$ python --version
Python 3.6.3
$ black --version
black, version 18.3a4
$ code --version
1.21.1
79b44aa704ce542d8ca4a3cc44cfca566e7720f1
x64
```

and this setting inside my .vscode/settings.json

```json
{
    "python.pythonPath": "${env.VIRTUAL_ENV}/bin/python",
    "python.formatting.provider": "none",
    "python.formatting.autopep8Args": [
        "--max-line-length", "100",
        "--aggressive",
        "--aggressive"
    ],
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "python.linting.flake8Args": ["--max-line-length=100"],
    "editor.snippetSuggestions": "top",
    "[python]": {
        "editor.tabSize": 4,
        "editor.insertSpaces": true
    },
    "[json]": {
        "editor.tabSize": 2,
        "editor.insertSpaces": true
    },
    "black.lineLength": 100
}
```

**Comment by joslarson** [comment]
@mhubig Thanks for the the well formed issue :) I can spot the problem right off. The extension currently only supports expansion of the `${workspaceFolder}` var in the `python.pythonPath` setting. I didn't realize the python extension allowed environment variables in the path.

**Comment by joslarson** [comment]
Wouldn't be too difficult to implement, but in the mean time a work around would be to make the `python.pythonPath` setting absolute.

**Comment by joslarson** [comment]
for future reference on this issue: https://code.visualstudio.com/docs/python/environments

**Comment by joslarson** [comment]
@mhubig black formatting support has landed in the official Python extension. I suggest switching to that and uninstalling this extension all together. That should resolve your issue. I am in the process of deprecating this extension. Let me know if there's any reason I shouldn't do that :)
